### PR TITLE
improve dnt build script

### PR DESCRIPTION
**Pull request by UrielCh**
please can you go to https://www.npmjs.com/settings/urielch/tokens
and create a new granular Access Token

image

then git if all access to Organization `denodnt` for 365 days

image

then add the token a `NPM_TOKEN` in [Repository secrets](https://github.com/deno-library/logger/settings/secrets/actions)

I do not have enough rights to do it.

### CODE REVIEW

**Comment by fuxingZhang** [comment]
dnt

I don't see this organization in my "Select organizations" list.

**Comment by fuxingZhang** [comment]
I've changed your role to admin.

image

**Comment by UrielCh** [comment]
Yeeeee!!!!

Done V 1.1.1 is out, and fully deployed by GitHub.

that it for today on this project.

thx for your reactivity.

**Comment by fuxingZhang** [comment]
It's amazing! 
Excellent work!

**Pull request merged**
